[package]
name = "mapli"
version = "0.1.0"
edition = "2024"

[lib]
name = "_core"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
# "abi3-py39" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.9
# "experimental-async" enables `async fn` in #[pymethods], which return native Python coroutines
pyo3 = { version = "0.29.3", features = ["extension-module", "abi3-py39", "experimental-async"] }
mapli-core = { path = "mapli-core" }

[workspace]
members = [".", "mapli-core"]
default-members = [".", "mapli-core"]
