[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
module-name = "mapli._core"
python-packages = ["mapli"]
python-source = "src"
editable-profile = "dev"
features = ["pyo3/extension-module"]

[project]
name = "mapli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ricardo Garcia Silva", email = "ricardo.garcia.silva@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "src/**/*.rs" },
    { file = "mapli-core/**/*.rs"},
    { file = "Cargo.toml" },
    { file = "Cargo.lock" }
]
