name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  run_ci:
    runs-on: ubuntu-24.04
    env:
      ARTIFACT_NAME: "python-package"
    outputs:
      artifact_name: ${{ env.ARTIFACT_NAME }}
    steps:
      - uses: actions/checkout@v7

      - name: "Format Rust code"
        run: cargo fmt --check

      - name: "Lint Rust code"
        run: cargo clippy -- --deny warnings

      - name: "Build Rust lib"
        run: cargo build --verbose

      - name: "Run Rust tests"
        run: cargo test --verbose

      - name: "Set up uv"
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0

      - name: "Set up Python"
        uses: actions/setup-python@v7
        with:
          python-version-file: "pyproject.toml"

      - name: "Install Python code with dev dependencies"
        run: uv sync --frozen --group dev

      - name: "Run ruff linter"
        run: uv run ruff check

      - name: "Run ruff formatter"
        run: uv run ruff format --check

      - name: "Run ty"
        run: uv run ty check

      - name: "Run Python tests"
        run: uv run pytest

      - name: "Build mapli wheel"
        run: uv build

      - name: "Upload built wheel as artifact"
        id: upload_package_artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          name: "${{ env.ARTIFACT_NAME }}"
          path: dist/
          retention-days: 2
